# Generated by Django 4.1.7 on 2023-09-13 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0003_remove_customuser_areas_customuser_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authentication_service.area'),
            preserve_default=False,
        ),
    ]
